name: Autoformatter
on: [push]
jobs:
  Execute-Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install black[jupyter]
          pip install mypy==0.812
          pip install pytest
          pip install pytest-cov
      - name: Run Linters
        run: |
          bash scripts/lint.sh
