name: Autoformatter
on: [push]
jobs:
  Execute-Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-dev.txt
      - name: Run Linters
        run: |
          bash scripts/lint.sh
