name: GitHub Actions Demo
on: [push]
jobs:
  Execute-Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-dev.txt
